name: rentmachine
region: nyc
services:
- name: backend
  dockerfile_path: backend/Dockerfile
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: eminemlose88/rentmachine
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: MONGODB_URL
    scope: RUN_TIME
    value: ${MONGODB_URL}
  - key: DATABASE_NAME
    scope: RUN_TIME
    value: rentmachine
  - key: SECRET_KEY
    scope: RUN_TIME
    value: ${SECRET_KEY}

- name: frontend
  dockerfile_path: frontend/Dockerfile
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: eminemlose88/rentmachine
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: API_URL
    scope: RUN_TIME
    value: ${APP_URL}/api/v1
